### PR TITLE
Fix icon colorizing at startup

### PR DESCRIPTION
**Pull request by tsujan**
Fixes https://github.com/lxde/lxqt/issues/1445.

### CODE REVIEW

**Comment by palinek** [comment]
GTM

**Comment by palinek** [comment]
Oh boy... actually this is not good, because the `createIconEngine()` is called for (almost) each icon, that is created by the `QIcon::fromTheme()` :(

We should put the `setFollowColorScheme()` call into the constructor after loading the configuration.

**Comment by tsujan** [comment]
@palinek Read this: https://github.com/lxde/lxqt-qtplugin/pull/33#issuecomment-365238215

**Comment by tsujan** [comment]
> Oh boy... actually this is not good, because the createIconEngine() is called for (almost) each icon,

And `setFollowColorScheme` does nothing if the variable in question isn't changed.

**Pull request merged**
