### PR TITLE
Remove unused parameter from onServiceOwnerChanged

### PR DESCRIPTION
**Pull request by jubalh**
Seems that they are not needed.

### CODE REVIEW

**Comment by palinek** [comment]
I personally would just comment the unused parameter names (or use the Q_UNUSED macro)... but GTM

**Comment by tsujan** [comment]
I wanted to say exactly what @palinek said.

**Comment by jubalh** [comment]
@palinek, @tsujan better?
What's better about this approach (curious)?

**Comment by palinek** [comment]
> What's better about this approach (curious)?

Just that the signal provides this information... and in the future you (the developer) can spot it directly while looking at the slog w/o knowing anything about the connected signal...nothing more.

But as I said... it was GTM even before.

**Pull request merged**
